### ISSUE TITLE
Hide packages and releases if not being used

### ISSUE THREAD

**Issue by avneesh0612** [krishguptadev/open-source-best-practices#10]
If the packages and releases are not being used, it is good to hide it :) 
![image](https://user-images.githubusercontent.com/76690419/144569513-53bdff06-30f6-4091-8f62-9184e51d74ca.png)

**Comment by suitupstan** [comment]
Packages I am hiding, but releases can be used

**Comment by avneesh0612** [comment]
Okay. I thought you should hide it until you use it 🤔

**Comment by suitupstan** [comment]
You can open up a issue for using them ;)

**Comment by avneesh0612** [comment]
haha lol
