### ISSUE TITLE
Open Source best practices resource example

### ISSUE THREAD

**Issue by NS007-dev** [krishguptadev/open-source-best-practices#15]
### What would you like to share?

@krishguptadev if you would like resources are the below ok?

- https://github.com/alexandresanlim/Badges4-README.md-Profile custom badges you can add to your open source. For example social media, which then links to making your repo popular.
- https://liyasthomas.github.io/banner/ make your own banner, which makes your repo bright and more attractive.
- https://shields.io/ original badges for repo.

Thank you, if this is right, please can you assign me to this, and I will work on this.

**Comment by suitupstan** [comment]
Not sure about the banner one 🤔 But we want to focus of best practices rather resources in the starting stage
