### ISSUE TITLE
[FEAT] Dependabot

### ISSUE THREAD

**Issue by suitupstan** [krishguptadev/open-source-best-practices#20]
### Describe the feature

- [x] Setup Dependabot `Weekly`
- [x] Allow it to update github action workflows 

### Describe the solution you'd like

You can use this doc to seek help: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

### Describe alternatives you've considered

-

**Comment by 0xMukesh** [comment]
@krishguptadev can i be assigned for this issue ?

**Comment by suitupstan** [comment]
Sure, @Kira272921 🎉
