### ISSUE TITLE
Create Issue templates

### ISSUE THREAD

**Issue by avneesh0612** [krishguptadev/open-source-best-practices#3]
A few basic issue templates are needed. You can refer to these- https://github.com/avneesh0612/.github/tree/main/.github/ISSUE_TEMPLATE

**Comment by lem0n4id** [comment]
We could use the latest issue forms using the `.yml` syntax. 
You can refer to this- https://github.com/EddieHubCommunity/LinkFree/tree/main/.github/ISSUE_TEMPLATE

[GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by 0xMukesh** [comment]
Hey @krishguptadev, Can I work on this ?

**Comment by suitupstan** [comment]
Sure @Kira272921 👍

**Comment by 0xMukesh** [comment]
@krishguptadev Created a PR #11
