### ISSUE TITLE
Create Pull Request template

### ISSUE THREAD

**Issue by lem0n4id** [krishguptadev/open-source-best-practices#5]
A pull request template is needed. 
You can refer to this- https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Pradumnasaraf** [comment]
I can go with this

**Comment by suitupstan** [comment]
Sure! Assigned!

**Comment by Pradumnasaraf** [comment]
> Sure! Assigned!

Thanks!!
