### ISSUE TITLE
[FEAT] Gitpodify Project

### ISSUE THREAD

**Issue by lem0n4id** [krishguptadev/open-source-best-practices#8]
add a best practice about integrating gitpod in open source projects

**Comment by lem0n4id** [comment]
I would love to take up this issue

**Comment by lem0n4id** [comment]
This issue is open for contribution. Feel free to take it up ❤️

**Comment by avneesh0612** [comment]
Hey, can I take this one? And can you tell where to add the badge?

**Comment by suitupstan** [comment]
> Hey, can I take this one? And can you tell where to add the badge?

It is all good until you follow https://www.gitpod.io/blog/gitpodify/

**Comment by avneesh0612** [comment]
okay
